services:
  auth-service:
    image: ${DOCKER_IMAGE}:dev
    container_name: ${AUTH_SERVICE_NAME}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    networks:
      - mumulbo-network
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: ${AUTH_SERVICE_NAME}-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - mumulbo-network
    restart: unless-stopped

networks:
  mumulbo-network:
    external: true
    driver: bridge
    name: ${MMB_DOCKER_NETWORK}