version: '3.8'
services:
  auth-service:
    build:
      dockerfile: ./Dockerfile
    container_name: mmb-auth-service
    ports:
      - 8080:${AUTH_SERVICE_PORT}
    environment:
      AUTH_SERVICE_NAME: ${AUTH_SERVICE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      MEMBER_SERVICE_HOST: ${MEMBER_SERVICE_HOST}
      MEMBER_SERVICE_PORT: ${MEMBER_SERVICE_PORT}
    #    restart: always
